// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.15.8
// source: seed_generation.proto

package seed_generation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GetSeedRequest) Reset() {
	*x = GetSeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_generation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeedRequest) ProtoMessage() {}

func (x *GetSeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seed_generation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeedRequest.ProtoReflect.Descriptor instead.
func (*GetSeedRequest) Descriptor() ([]byte, []int) {
	return file_seed_generation_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeedRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetSeedRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetSeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed  int64 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetSeedResponse) Reset() {
	*x = GetSeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_generation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeedResponse) ProtoMessage() {}

func (x *GetSeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seed_generation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeedResponse.ProtoReflect.Descriptor instead.
func (*GetSeedResponse) Descriptor() ([]byte, []int) {
	return file_seed_generation_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeedResponse) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GetSeedResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StressTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StressTestRequest) Reset() {
	*x = StressTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_generation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StressTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StressTestRequest) ProtoMessage() {}

func (x *StressTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seed_generation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StressTestRequest.ProtoReflect.Descriptor instead.
func (*StressTestRequest) Descriptor() ([]byte, []int) {
	return file_seed_generation_proto_rawDescGZIP(), []int{2}
}

func (x *StressTestRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StressTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response int64 `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *StressTestResponse) Reset() {
	*x = StressTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_generation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StressTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StressTestResponse) ProtoMessage() {}

func (x *StressTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seed_generation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StressTestResponse.ProtoReflect.Descriptor instead.
func (*StressTestResponse) Descriptor() ([]byte, []int) {
	return file_seed_generation_proto_rawDescGZIP(), []int{3}
}

func (x *StressTestResponse) GetResponse() int64 {
	if x != nil {
		return x.Response
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping int64 `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_generation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seed_generation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_seed_generation_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetPing() int64 {
	if x != nil {
		return x.Ping
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response int64 `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_generation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seed_generation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_seed_generation_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetResponse() int64 {
	if x != nil {
		return x.Response
	}
	return 0
}

var File_seed_generation_proto protoreflect.FileDescriptor

var file_seed_generation_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x29, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x12, 0x53, 0x74,
	0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x0a, 0x0b,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22,
	0x2a, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x87, 0x02, 0x0a, 0x15,
	0x53, 0x65, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x65, 0x65, 0x64,
	0x12, 0x1f, 0x2e, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e,
	0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65,
	0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0a,
	0x53, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x65,
	0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x72, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seed_generation_proto_rawDescOnce sync.Once
	file_seed_generation_proto_rawDescData = file_seed_generation_proto_rawDesc
)

func file_seed_generation_proto_rawDescGZIP() []byte {
	file_seed_generation_proto_rawDescOnce.Do(func() {
		file_seed_generation_proto_rawDescData = protoimpl.X.CompressGZIP(file_seed_generation_proto_rawDescData)
	})
	return file_seed_generation_proto_rawDescData
}

var file_seed_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_seed_generation_proto_goTypes = []any{
	(*GetSeedRequest)(nil),     // 0: seed_generation.GetSeedRequest
	(*GetSeedResponse)(nil),    // 1: seed_generation.GetSeedResponse
	(*StressTestRequest)(nil),  // 2: seed_generation.StressTestRequest
	(*StressTestResponse)(nil), // 3: seed_generation.StressTestResponse
	(*PingRequest)(nil),        // 4: seed_generation.PingRequest
	(*PingResponse)(nil),       // 5: seed_generation.PingResponse
}
var file_seed_generation_proto_depIdxs = []int32{
	0, // 0: seed_generation.SeedGenerationService.GetSeed:input_type -> seed_generation.GetSeedRequest
	4, // 1: seed_generation.SeedGenerationService.Ping:input_type -> seed_generation.PingRequest
	2, // 2: seed_generation.SeedGenerationService.StressTest:input_type -> seed_generation.StressTestRequest
	1, // 3: seed_generation.SeedGenerationService.GetSeed:output_type -> seed_generation.GetSeedResponse
	5, // 4: seed_generation.SeedGenerationService.Ping:output_type -> seed_generation.PingResponse
	3, // 5: seed_generation.SeedGenerationService.StressTest:output_type -> seed_generation.StressTestResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seed_generation_proto_init() }
func file_seed_generation_proto_init() {
	if File_seed_generation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seed_generation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_generation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_generation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StressTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_generation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StressTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_generation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_generation_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seed_generation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seed_generation_proto_goTypes,
		DependencyIndexes: file_seed_generation_proto_depIdxs,
		MessageInfos:      file_seed_generation_proto_msgTypes,
	}.Build()
	File_seed_generation_proto = out.File
	file_seed_generation_proto_rawDesc = nil
	file_seed_generation_proto_goTypes = nil
	file_seed_generation_proto_depIdxs = nil
}
